; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/cache
default_envs = 
    esp32_temperature_sensor
    esp32_temperature_sensor_oled

[env:esp32_temperature_sensor]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<temperature_sensor.cpp> +<HueMixLink.h>
build_flags = 
	-DFIRMWARE_VERSION=\"1.0.3\"
lib_deps =
	adafruit/Adafruit SHT31 Library@^2.2.2
lib_compat_mode = strict

[env:esp32_temperature_sensor_oled]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<temperature_sensor_oled.cpp> +<HueMixLink.h>
build_flags =
	-DFIRMWARE_VERSION=\"1.0.0\"
lib_deps =
	adafruit/Adafruit SHT31 Library@^2.2.2
	adafruit/Adafruit SH110X@^2.1.13
lib_compat_mode = strict
